GET http://localhost:3000//products

###

GET http://localhost:3000/products/50.json

###

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "input_name": "keyboard",
  "input_price": "50",
  "input_image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQ052?wid=4000&hei=1800&fmt=jpeg&qlt=95&.v=1495129815011",
  "input_desc": "type on this"
}

###
PATCH http://localhost:3000/products/52.json
Content-Type: application/json

{
  "input_price": "100",
  "input_name": "mouse",
  "input_price": 23,
  "input_image_url": "https://m.media-amazon.com/images/I/61UxfXTUyvL.jpg",
  "input_description": "use this with your pc"
}
