### get all products
GET http://localhost:3000//products.json

### get specific product
GET http://localhost:3000/products/52.json

### create data
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzQxNTk1ODB9.i3fq5NkbK5EuYU4YpzKJFyQDja0fZJIDlf5StKFkPLw
Content-Type: application/json

{
  "name": "testtttt",
  "price": "100",
  "description": "this is how you test things",
  "supplier_id": "1"
}

### update data
PATCH http://localhost:3000/products/115.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzQxNTk1ODB9.i3fq5NkbK5EuYU4YpzKJFyQDja0fZJIDlf5StKFkPLw
Content-Type: application/json

{
  "price": "200",
  "name": "other test",
  "description": "this is me testing",
  "supplier_id": "2"
}

### destroy data
DELETE http://localhost:3000/products/66.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Other Test name",
  "email": "testthesecond@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "testthesecond@test.com",
  "password": "password"
}

### order create
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzE1NjgxNjF9.6zZ8u8VFaDz96wKNAgBXB25NV9hs4IKoz2Q2EjXtxHk

### orders show
GET http://localhost:3000/orders/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzE2NTQyODR9.-RafWKXqTf7xEFNSePSjS_IVrT3V9us5h4P3vhyM89w


### orders index
GET http://localhost:3000//orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzE1NjgxNjF9.6zZ8u8VFaDz96wKNAgBXB25NV9hs4IKoz2Q2EjXtxHk

### carted_products create
POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzE1NjgxNjF9.6zZ8u8VFaDz96wKNAgBXB25NV9hs4IKoz2Q2EjXtxHk
Content-Type: application/json

{
  "product_id": 112,
  "quantity": 1
}

### carted_products index
GET http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzE1NjgxNjF9.6zZ8u8VFaDz96wKNAgBXB25NV9hs4IKoz2Q2EjXtxHk

### destroy carted_products
DELETE http://localhost:3000/carted_products/11.json