### get all products
GET http://localhost:3000//products.json

### get specific product
GET http://localhost:3000/products/52.json

### create data
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test computer",
  "price": "2000",
  "description": "testing create data",
   "image_url": []
}

### update data
PATCH http://localhost:3000/products/52.json
Content-Type: application/json

{
  "price": "500",
  "name": "monitor",
  "image_url": "https://www.lg.com/us/images/monitors/md06064916/gallery/desktop-03.jpg",
  "description": "view your stuff"
}

### destroy data
DELETE http://localhost:3000/products/66.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

###
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": "1",
  "product_id": "52",
  "quantity": "1",
  "subtotal": "10",
  "tax": 2,
  "total": 12
}

### orders show
GET http://localhost:3000/orders/2.json

### orders index
GET http://localhost:3000//orders.json